2020-01-17 11:04:53 INFO  Operation directory: /Users/brunoguedes/RafaelPOC/datastax/logs/LOAD_20200117-110453-841849
2020-01-17 11:05:24 WARN  [s0] Error connecting to Node(endPoint=/10.0.0.123:9042, hostId=null, hashCode=1ea1c235), trying next node (ConnectionInitException: [s0|control|connecting...] init query OPTIONS: error writing )
2020-01-17 11:05:24 ERROR Operation LOAD_20200117-110453-841849 failed: Could not reach any contact point, make sure you've provided valid addresses (showing first 1, use getErrors() for more: Node(endPoint=/10.0.0.123:9042, hostId=null, hashCode=1ea1c235): com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|connecting...] init query OPTIONS: error writing ).
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1, use getErrors() for more: Node(endPoint=/10.0.0.123:9042, hostId=null, hashCode=1ea1c235): com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|connecting...] init query OPTIONS: error writing )
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:95)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:501)
	at com.datastax.dsbulk.engine.internal.settings.DriverSettings.newSession(DriverSettings.java:566)
	at com.datastax.dsbulk.engine.LoadWorkflow.init(LoadWorkflow.java:122)
	at com.datastax.dsbulk.engine.DataStaxBulkLoader$WorkflowThread.run(DataStaxBulkLoader.java:127)
